" Auto installation of vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Plugins
Plug 'tpope/vim-commentary'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree'
Plug 'dense-analysis/ale'
Plug 'ayu-theme/ayu-vim'

" Initialize plugin system
call plug#end()

" Show line numbers
set number

" Enable syntax highlighting
syntax on
filetype plugin on
filetype indent on

" Function to set colorscheme based on system preference
function! SetSystemColorscheme()
  let l:system_theme = system("~/.vim/get_color_scheme_light_dark.sh")
  let l:system_theme = substitute(l:system_theme, '[\n\r]*$', '', '') " Remove newlines

  if l:system_theme == "light"
    let g:ayucolor="light"
  else
    let g:ayucolor="mirage"
  endif

  colorscheme ayu
endfunction


set termguicolors

augroup SystemTheme
  autocmd!
  autocmd VimEnter * call SetSystemColorscheme()
augroup END

" Line length limiter
set colorcolumn=120

" Highlight all search results
set hlsearch
" Highlight as you type
set incsearch

set ignorecase
set smartcase

" Highlight TODO, FIXME, etc.. and trailing white space characters
match Todo /\s\+$/
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

" Indent settings
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent

" File Explorer - tree view
let g:netrw_liststyle = 3

" Underline current line
set cursorline

" Enable the markdown syntax highlight for .md files
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" Ale
nnoremap <silent> gd :ALEGoToDefinition<CR>
nnoremap <silent> K ::ALEHover<CR>
nnoremap <silent> <C-f> :ALEFindReferences<CR>
nnoremap <silent> gf :ALEFix<CR>
nnoremap <silent> <F2> :ALERename<CR>
set omnifunc=ale#completion#OmniFunc
let g:ale_fix_on_save = 1

" FZF
map <c-p> :FZF<cr>

" NERDTree
nnoremap <Leader>t :NERDTreeFocus<CR>
