" ##############
" Vundle options
" ##############

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')
"
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'


" Plugins
Plugin 'tpope/vim-commentary'
Plugin 'pangloss/vim-javascript'
Plugin 'danilo-augusto/vim-afterglow'
Plugin 'github-theme'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'easymotion/vim-easymotion'
Plugin 'flowtype/vim-flow'
Plugin 'w0rp/ale'
Plugin 'junegunn/fzf'
Plugin 'prettier/vim-prettier'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line




" #################
" Personal settings
" #################

" Show line numbers
set number

" Color scheme
colorscheme afterglow
" Clear theme
" colorscheme github

" Enable syntax highlighting
syntax on
filetype plugin on
filetype indent on

" Line length limiter
set colorcolumn=120

" Highlight all search results
set hlsearch

" Highlight TODO, FIXME, etc.. and trailing white space characters
match Todo /\s\+$/
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

" Indent settings
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent

" Enable the markdown syntax highlight for .md files
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" vim-flow related configuration
let g:flow#enable = 0
"Use locally installed flow
let local_flow = finddir('node_modules', '.;') . '/.bin/flow'
if matchstr(local_flow, "^\/\\w") == ''
    let local_flow= getcwd() . "/" . local_flow
endif
if executable(local_flow)
  let g:flow#flowpath = local_flow
endif

" vim-ale related options
let g:ale_lint_on_text_changed = 'never'

" Prettier
map <leader>p :Prettier<cr>
let g:prettier#config#single_quote = 'true'
let g:prettier#config#trailing_comma = 'none'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#parser = 'babylon'

" FZF
map <c-p> :FZF<cr>

" Underline current line
set cursorline


