" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Plugins
Plug 'tpope/vim-commentary'
Plug 'pangloss/vim-javascript'
Plug 'altercation/vim-colors-solarized'
Plug 'terryma/vim-multiple-cursors'
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/fzf'
Plug 'prettier/vim-prettier'
Plug 'reasonml-editor/vim-reason-plus'
Plug 'scrooloose/nerdtree'
Plug 'w0rp/ale'

" Initialize plugin system
call plug#end()

" Show line numbers
set number

" Color scheme
" set background=light
set background=dark
colorscheme solarized

" Enable syntax highlighting
syntax on
filetype plugin on
filetype indent on

" Line length limiter
set colorcolumn=80

" Highlight all search results
set hlsearch
" Highlight as you type
set incsearch

set ignorecase
set smartcase

" Highlight TODO, FIXME, etc.. and trailing white space characters
match Todo /\s\+$/
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

" Indent settings
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent

" File Explorer - tree view
let g:netrw_liststyle = 3

" Underline current line
set cursorline

" Enable the markdown syntax highlight for .md files
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" Prettier
map <leader>p :Prettier<cr>
let g:prettier#config#single_quote = 'true'
let g:prettier#config#trailing_comma = 'none'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#parser = 'babylon'
let g:prettier#exec_cmd_path = "prettier"

" Ale
nnoremap <silent> gd :ALEGoToDefinition<CR>
nnoremap <silent> K ::ALEHover<CR>
nnoremap <silent> <C-f> :ALEFindReferences<CR>
nnoremap <silent> gf :ALEFix<CR>
let g:ale_haskell_hie_executable = 'hie-wrapper'

" FZF
map <c-p> :FZF<cr>

" NERDTree
nnoremap <Leader>t :NERDTreeFocus<CR>
